// Generated by scripts/export_types.py from packages/schema/adschema.
// Do not edit — regenerate.  `scripts/export_types.py --check` fails on drift.
//
// Every field below is present on the wire: pydantic's `model_dump(mode="json")`
// emits defaulted fields, so `?:` would be wrong.  `| null` means Python says the
// value can genuinely be absent.
//
// Python `@property` values are NOT serialised.  Each interface lists its own
// under `derived (not on the wire)`; those are computed in `lib/presentation.ts`
// and tested in `lib/presentation.test.ts`.

/** ISO-8601 with an offset, e.g. "2026-08-12T09:41:07.123456+00:00". */
export type Timestamp = string;

// --- Constants ---

export const MIN_DURATION_S = 8;
export const MAX_DURATION_S = 10;
export const DEFAULT_CANDIDATE_COUNT = 3;

// --- Enumerations ---

/** Output geometry. Derived from `Platform` rather than asked for. */
export type AspectRatio = "9:16" | "4:5" | "1:1" | "16:9";
export const ASPECT_RATIO_VALUES: readonly AspectRatio[] = [
  "9:16",
  "4:5",
  "1:1",
  "16:9",
];

export type BackgroundTreatment =
  | "studio_white"
  | "seamless_color"
  | "soft_gradient"
  | "lifestyle_scene"
  | "outdoor_natural";
export const BACKGROUND_TREATMENT_VALUES: readonly BackgroundTreatment[] = [
  "studio_white",
  "seamless_color",
  "soft_gradient",
  "lifestyle_scene",
  "outdoor_natural",
];

export type CameraAngle =
  | "eye_level"
  | "low_angle"
  | "high_angle"
  | "three_quarter"
  | "profile"
  | "close_up_product";
export const CAMERA_ANGLE_VALUES: readonly CameraAngle[] = [
  "eye_level",
  "low_angle",
  "high_angle",
  "three_quarter",
  "profile",
  "close_up_product",
];

export type Composition =
  | "centered_hero"
  | "rule_of_thirds_left"
  | "rule_of_thirds_right"
  | "negative_space_top"
  | "product_foreground";
export const COMPOSITION_VALUES: readonly Composition[] = [
  "centered_hero",
  "rule_of_thirds_left",
  "rule_of_thirds_right",
  "negative_space_top",
  "product_foreground",
];

/**
 * Quality-gate outcome. Deliberately separate from the learned score: the gate answers
 * "is this usable at all", the predictor answers "how well will it perform".
 * Conflating the two is how these systems get muddled.
 */
export type GateVerdict = "pass" | "retry" | "reject";
export const GATE_VERDICT_VALUES: readonly GateVerdict[] = [
  "pass",
  "retry",
  "reject",
];

export type JobState =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "refused_over_budget";
export const JOB_STATE_VALUES: readonly JobState[] = [
  "queued",
  "running",
  "completed",
  "failed",
  "refused_over_budget",
];

export type Lighting =
  | "soft_diffused"
  | "hard_directional"
  | "rim_backlit"
  | "golden_hour"
  | "high_key";
export const LIGHTING_VALUES: readonly Lighting[] = [
  "soft_diffused",
  "hard_directional",
  "rim_backlit",
  "golden_hour",
  "high_key",
];

/** Single user-facing energy control. Drives lighting and motion intent. */
export type Mood =
  | "calm_premium"
  | "warm_lifestyle"
  | "bold_confident"
  | "high_energy";
export const MOOD_VALUES: readonly Mood[] = [
  "calm_premium",
  "warm_lifestyle",
  "bold_confident",
  "high_energy",
];

/** What the image-to-video stage should animate. */
export type MotionIntent =
  | "slow_dolly_in"
  | "slow_dolly_out"
  | "orbit_left"
  | "product_present"
  | "handheld_drift"
  | "static_subtle";
export const MOTION_INTENT_VALUES: readonly MotionIntent[] = [
  "slow_dolly_in",
  "slow_dolly_out",
  "orbit_left",
  "product_present",
  "handheld_drift",
  "static_subtle",
];

/** Delivery target. Drives aspect ratio and the safe-area overlay. */
export type Platform =
  | "instagram_reels"
  | "instagram_feed"
  | "instagram_story"
  | "youtube_shorts"
  | "youtube_instream"
  | "tiktok"
  | "facebook_feed";
export const PLATFORM_VALUES: readonly Platform[] = [
  "instagram_reels",
  "instagram_feed",
  "instagram_story",
  "youtube_shorts",
  "youtube_instream",
  "tiktok",
  "facebook_feed",
];

/** How generations are obtained. */
export type ProviderMode = "mock" | "live" | "replay";
export const PROVIDER_MODE_VALUES: readonly ProviderMode[] = [
  "mock",
  "live",
  "replay",
];

/** The eight pipeline stages, in order. Emitted over SSE for progress. */
export type Stage =
  | "intake"
  | "brief"
  | "image_gen"
  | "quality_gate"
  | "image_rank"
  | "video_gen"
  | "video_rank"
  | "delivery";
export const STAGE_VALUES: readonly Stage[] = [
  "intake",
  "brief",
  "image_gen",
  "quality_gate",
  "image_rank",
  "video_gen",
  "video_rank",
  "delivery",
];

/** Which generation tier served a candidate. */
export type Tier = "research" | "premium" | "mock";
export const TIER_VALUES: readonly Tier[] = [
  "research",
  "premium",
  "mock",
];

/**
 * Product category. A real predictor feature — click behaviour differs enormously
 * between, say, beauty and electronics, so the ranker conditions on it rather than
 * treating all ads alike.
 */
export type Vertical =
  | "apparel"
  | "beauty"
  | "food_beverage"
  | "electronics"
  | "jewellery"
  | "fitness"
  | "home"
  | "footwear"
  | "other";
export const VERTICAL_VALUES: readonly Vertical[] = [
  "apparel",
  "beauty",
  "food_beverage",
  "electronics",
  "jewellery",
  "fitness",
  "home",
  "footwear",
  "other",
];

// --- Models ---

/** Everything needed to run one 3-candidate ad job. */
// derived (not on the wire): aspect_ratio
export interface AdJobRequest {
  job_id: string;
  created_at: Timestamp;
  human_model_image: AssetRef;
  product_image: AssetRef;
  logo_image: AssetRef | null;
  /** Min length 1; max length 120. */
  product_name: string;
  /** Max length 300. */
  caption: string;
  /** e.g. 'Shop now' (max length 40) */
  cta_text: string;
  /** Max length 1000. */
  additional_prompt: string;
  /**
   * Free text, e.g. 'no hands covering the label, no visible text on product' (max
   * length 500)
   */
  negative_constraints: string;
  vertical: Vertical;
  platform: Platform;
  audience: AudienceSpec;
  theme: ThemeSpec;
  mood: Mood;
  /** Advanced panel only; normally derived from platform. */
  aspect_ratio_override: AspectRatio | null;
  /** Video length. Kept in the 8-10 s window the project commits to. (range 8.0–10.0) */
  duration_seconds: number;
  /** Range 1–6. */
  candidate_count: number;
  /**
   * Pin the camera angle across all candidates. Left None, the sampler varies angle —
   * which is what makes the candidates genuinely different.
   */
  locked_angle: CameraAngle | null;
  /**
   * Base seed. Candidate i uses seed + i, so runs are reproducible and ablations are
   * comparable. (at least 0)
   */
  seed: number;
  consent: ConsentAttestation;
  tier: Tier;
}

/** What the UI needs to render honestly: the mode, and what it costs. */
export interface AppConfig {
  provider_mode: ProviderMode;
  /** True only when real provider calls are armed. */
  is_live: boolean;
  /** True when output comes from a frozen bundle. */
  is_replay: boolean;
  image_provider: string;
  video_provider: string;
  /** Slug replayed in replay mode, else null. */
  golden_set: string | null;
  /**
   * The settings banner verbatim. It names the providers actually wired up, which is
   * the difference between 'live mode' and 'live mode, but the video provider fell
   * back to a mock'.
   */
  banner: string;
  /**
   * Every platform's derived geometry, so the wizard reads it rather than hardcoding a
   * ratio that then disagrees with the renderer.
   */
  platforms: Partial<Record<Platform, PlatformProfile>>;
}

/**
 * A pointer to a stored upload. Never raw bytes — media lives in object storage and
 * moves around as a key plus a signed URL.
 */
export interface AssetRef {
  /** Storage key, e.g. 'uploads/<job>/human.jpg' */
  key: string;
  /** Signed URL, short-lived */
  url: string | null;
  mime_type: string;
  width: number | null;
  height: number | null;
  /** Content hash, for the cache key */
  sha256: string | null;
}

/** Who the ad is for. Feeds the predictor as tabular context. */
export interface AudienceSpec {
  age_band: string;
  /** Min length 2; max length 8. */
  region: string;
  /** Min length 2; max length 8. */
  language: string;
}

/** The mix, with the provenance required to publish it. */
export interface AudioReport {
  attached: boolean;
  credit: string;
  licence: string;
  target_lufs: number | null;
  measured_lufs: number | null;
  has_voiceover: boolean;
  /**
   * True when the bed is a synthesised tone rather than music. Keeps a development
   * placeholder from being described as a soundtrack.
   */
  is_test_signal: boolean;
  note: string;
}

/** All briefs for one job, plus the diversity metric the sampler achieved. */
export interface BriefSet {
  job_id: string;
  briefs: ShotBrief[];
  /**
   * Minimum Hamming distance between any two design points. Reported as the sampler's
   * diversity guarantee; 0 means duplicates exist.
   */
  min_pairwise_distance: number;
  /** Which sampler produced these. */
  sampler: string;
}

/** A snapshot the UI shows and the governor enforces. */
// derived (not on the wire): remaining_usd, fraction_used
export interface BudgetStatus {
  total_budget_usd: number;
  spent_usd: number;
  per_job_cap_usd: number;
}

/** Affirmative rights confirmation for the human-model image. */
// derived (not on the wire): is_valid
export interface ConsentAttestation {
  /** User confirms they hold rights to use this person's likeness. */
  has_model_release: boolean;
  /** User confirms the image is not of a public figure or celebrity. */
  not_a_public_figure: boolean;
  attested_at: Timestamp;
  attested_by: string | null;
}

/** Whether the product was successfully separated from its background. */
export interface CutoutReport {
  /** 'rembg' (trained matting), 'flood-fill' (numpy fallback), or 'none'. */
  method: string;
  /**
   * False when no cutout was produced, or one was produced and rejected by its own
   * sanity check. The original product image is used instead.
   */
  accepted: boolean;
  /** Transparent PNG, when accepted. */
  asset: AssetRef | null;
  /**
   * Opaque fraction of the cutout. Near 1.0 means nothing was removed; near 0.0 means
   * the subject was removed along with the background. (range 0.0–1.0)
   */
  coverage: number | null;
  /** How flat the source backdrop was. Gates the flood-fill fallback. (range 0.0–1.0) */
  border_uniformity: number | null;
  detail: string;
}

/** Stage 8's output for one job. */
// derived (not on the wire): worst_reframe
export interface DeliveryReport {
  renders: ReframeReport[];
  /**
   * Platform mockup frames, keyed by platform value. The video frame with the
   * platform's chrome overlaid, so a product sitting under the caption bar is visible
   * before publishing rather than after.
   */
  previews: Record<string, AssetRef>;
  audio: AudioReport;
  /** Zip of every render, preview and report card. */
  bundle: AssetRef | null;
  warnings: string[];
}

/** Stage 8's output on its own, without re-fetching the whole record. */
export interface DeliveryResponse {
  job_id: string;
  summary: string;
  delivery: DeliveryReport;
  /** Null until the bundle has been written. */
  download_url: string | null;
}

/** One sampled coordinate in the creative design space. */
export interface DesignPoint {
  /** Candidate slot this point belongs to. (at least 0) */
  index: number;
  angle: CameraAngle;
  lighting: Lighting;
  composition: Composition;
  motion: MotionIntent;
  seed: number;
}

/** Face presence in the human-model reference. */
export interface FaceReport {
  /** 'opencv-haar' or 'unavailable'. */
  detector: string;
  /** False when no detector was available to run. */
  implemented: boolean;
  /** At least 0. */
  faces_found: number;
  /** Largest face as [x, y, w, h] in source pixels. */
  box: number[] | null;
  /** Face area as a fraction of the frame. (range 0.0–1.0) */
  box_area_fraction: number | null;
  detail: string;
}

/** One hard filter's outcome. */
export interface GateCheck {
  /** e.g. 'product_identity', 'face_identity', 'palette_delta_e' */
  name: string;
  value: number;
  threshold: number;
  passed: boolean;
  higher_is_better: boolean;
  detail: string;
  /**
   * False for checks whose model has not landed yet (DINOv2 product identity, ArcFace
   * face identity). A pending check always passes, so it must be visibly
   * distinguishable from one that genuinely verified something — otherwise the write-
   * up would claim identity verification that never ran.
   */
  implemented: boolean;
}

/** The full quality-control verdict for a candidate. */
// derived (not on the wire): failures, pending_checks, verified_identity, reason
export interface GateResult {
  verdict: GateVerdict;
  checks: GateCheck[];
  /** 1 = first try, 2 = after the one retry. (at least 1) */
  attempt: number;
}

/** One frozen demo bundle, as the job board lists it. */
export interface GoldenSummary {
  slug: string;
  title: string;
  /** ISO-8601, as recorded in the bundle manifest. */
  created_at: string;
  summary: string;
  /** At least 0. */
  frames: number;
  /** At least 0. */
  clips: number;
  image_model: string;
  video_model: string;
  /** What the bundle cost when it was frozen. A replay costs zero. (at least 0.0) */
  original_cost_usd: number;
  replayable: boolean;
  problems: string[];
  /**
   * Candidate slot the frozen run ranked first, when the bundle records an expectation
   * to check the replay against.
   */
  winner_slot: number | null;
}

/** One generated ad frame. */
// derived (not on the wire): passed_gate
export interface ImageCandidate {
  /** At least 0. */
  index: number;
  brief: ShotBrief;
  asset: AssetRef;
  tier: Tier;
  provider: string;
  seed: number;
  /** At least 0.0. */
  cost_usd: number;
  /** At least 0. */
  latency_ms: number;
  created_at: Timestamp;
  gate: GateResult | null;
  /** Image-stage prediction. Only set once the gate passes. */
  score: ScoreBreakdown | null;
}

/** Everything stage 1 established about the uploads. */
// derived (not on the wire): unusable, blocking_reason, all_advisories
export interface IntakeReport {
  references: ReferenceReport[];
  /** Resolved brand palette, supplied or extracted. */
  palette: string[];
  /** Coverage of each palette colour in its source region. */
  palette_weights: number[];
  /**
   * 'user', 'product-cutout', 'product-frame', or 'none'. Recorded because a palette
   * read off a whole photograph includes its backdrop, which is a materially weaker
   * constraint than one read from inside the product mask.
   */
  palette_source: string;
  cutout: CutoutReport;
  face: FaceReport;
  /** Job-level guidance. */
  advisories: string[];
}

/** One page of the job board, and the count it is a page *of*. */
// derived (not on the wire): has_more
export interface JobPage {
  jobs: JobSummary[];
  /** Every job in the store, not just this page. (at least 0) */
  total: number;
  /** At least 1. */
  limit: number;
  /** At least 0. */
  offset: number;
}

/** The persisted job: request, state, progress history and results. */
// derived (not on the wire): job_id, current_stage, duration_seconds
export interface JobRecord {
  request: AdJobRequest;
  state: JobState;
  result: JobResult | null;
  events: StageEvent[];
  error: string | null;
  /** Set when the governor refused the job over budget. */
  refusal_reason: string | null;
  started_at: Timestamp | null;
  finished_at: Timestamp | null;
}

/** Everything the pipeline produced for one job. */
// derived (not on the wire): winner, image_stage_order, video_stage_order
export interface JobResult {
  job_id: string;
  /**
   * What stage 1 made of the uploads: which were usable, where the palette came from,
   * whether a product cutout was produced.
   */
  intake: IntakeReport | null;
  briefs: BriefSet | null;
  images: ImageCandidate[];
  videos: VideoCandidate[];
  ranking: RankedCandidate[];
  /**
   * What stage 8 produced: platform renders and how lossy each reframe was, mockup
   * previews, the audio mix's provenance, and the bundle.
   */
  delivery: DeliveryReport | null;
  /** At least 0.0. */
  total_cost_usd: number;
}

/** A row on the job board, which is deliberately not the whole record. */
export interface JobSummary {
  job_id: string;
  state: JobState;
  product_name: string;
  platform: Platform;
  /** ISO-8601 of the request, not of the result. */
  created_at: string;
  /** At least 0.0. */
  cost_usd: number;
  /** Source image index of the top-ranked video, if ranked. */
  winner: number | null;
}

/** Acknowledgement of a job that has been queued but has not run yet. */
export interface Launched {
  job_id: string;
  state: JobState;
  /** Set when this job is a replay of a frozen bundle. */
  golden_set: string | null;
  /** Summary of the bundle being replayed, if any. */
  replaying: string | null;
}

/** Every charge attributed to one job. */
export interface LedgerResponse {
  job_id: string;
  /** At least 0.0. */
  total_usd: number;
  entries: SpendEntry[];
}

/** Geometry the UI derives from the chosen platform rather than asking for. */
export interface PlatformProfile {
  aspect_ratio: AspectRatio;
  safe_area: SafeAreaBox;
}

/** A video candidate placed in the final ordering, with its explanation. */
// derived (not on the wire): rank_shift
export interface RankedCandidate {
  /** At least 1. */
  rank: number;
  video: VideoCandidate;
  /** Human-readable justification built from the score components. */
  explanation: string;
  /**
   * Where this candidate ranked before video generation. The agreement between this
   * and `rank` is the project's headline measurement. (at least 1)
   */
  image_stage_rank: number | null;
}

/** Per-upload validation outcome. */
// derived (not on the wire): failures, usable, reason
export interface ReferenceReport {
  /** 'human_model' | 'product' | 'logo' */
  role: string;
  asset: AssetRef;
  /** At least 0. */
  width: number;
  /** At least 0. */
  height: number;
  /** Blocking checks only. A failure here refuses the job. */
  checks: GateCheck[];
  /**
   * Measured and reported but never blocking. A measurement is here rather than in
   * `checks` when the quantity is real but its threshold is not yet calibrated against
   * real uploads — recording the value on every job is what makes that calibration
   * possible later.
   */
  measurements: GateCheck[];
  /** Non-blocking guidance shown to the user, e.g. a soft or small upload. */
  advisories: string[];
}

/** One aspect-ratio variant, and the cost of producing it. */
// derived (not on the wire): improvement_over_centre
export interface ReframeReport {
  /** e.g. '9:16' */
  aspect_ratio: string;
  asset: AssetRef;
  /** 'crop' | 'pad' | 'none' */
  mode: string;
  /** At least 1. */
  width: number;
  /** At least 1. */
  height: number;
  /**
   * Share of attention-weighted content the reframe kept. 1.0 for a no-op; a padded
   * variant keeps everything visible but smaller, so its figure describes what a crop
   * *would* have kept and is why padding was chosen. (range 0.0–1.0)
   */
  retained_salience: number;
  /**
   * What a naive centre crop would have kept. Carried so the smart crop's benefit is a
   * comparison rather than an unanchored number. (range 0.0–1.0)
   */
  centre_crop_salience: number | null;
  /**
   * Extra salience a per-frame tracking window would have kept. The price of holding
   * the crop still, which is paid deliberately: a jittering frame is worse to watch
   * than a slightly mis-framed steady one.
   */
  tracking_gain: number;
  note: string;
}

/** Fractions of each edge that platform chrome may cover. */
export interface SafeAreaBox {
  /** Range 0.0–1.0. */
  top: number;
  /** Range 0.0–1.0. */
  bottom: number;
  /** Range 0.0–1.0. */
  left: number;
  /** Range 0.0–1.0. */
  right: number;
}

/** Predicted performance, decomposed. */
export interface ScoreBreakdown {
  /** Calibrated performance prediction. (range 0.0–1.0) */
  overall: number;
  /** Range 0.0–1.0. */
  aesthetic: number | null;
  /** Range 0.0–1.0. */
  prompt_alignment: number | null;
  /** Attention proxy: product's share of saliency. (range 0.0–1.0) */
  product_salience: number | null;
  /** Range 0.0–1.0. */
  composition: number | null;
  /** Range 0.0–1.0. */
  palette_adherence: number | null;
  /** Range 0.0–1.0. */
  temporal_consistency: number | null;
  /** Range 0.0–1.0. */
  motion_quality: number | null;
  /** How arresting the first second is. (range 0.0–1.0) */
  hook_strength: number | null;
  /** Fraction of frames the product is visible in. (range 0.0–1.0) */
  product_screen_time: number | null;
  /** Range 0.0–1.0. */
  safe_area_compliance: number | null;
  /** Which predictor produced this. */
  model_version: string;
  /**
   * True until the trained head lands. Prevents stub numbers being mistaken for real
   * predictions in the write-up.
   */
  is_stub: boolean;
}

/** A single candidate's full creative instruction set. */
// derived (not on the wire): slot_label
export interface ShotBrief {
  /** At least 0. */
  index: number;
  design_point: DesignPoint;
  /**
   * Multi-reference composition prompt. Must name the reference roles explicitly
   * ('Image 1 is the model...') — vague prompts cause identity drift.
   */
  image_prompt: string;
  negative_prompt: string;
  /** Image-to-video instruction applied to this candidate's frame. */
  motion_prompt: string;
  /** One-line description of the creative idea. */
  concept: string;
}

/** One line in the cost ledger. */
export interface SpendEntry {
  entry_id: string;
  job_id: string | null;
  provider: string;
  /** 'image' | 'video' | 'llm' */
  operation: string;
  model: string;
  /** Images, or seconds of video. */
  quantity: number;
  /** At least 0.0. */
  unit_cost_usd: number;
  /** At least 0.0. */
  cost_usd: number;
  /** Cache hits are recorded at zero cost. */
  cache_hit: boolean;
  at: Timestamp;
  note: string;
}

/** One progress tick, streamed to the UI over SSE. */
// derived (not on the wire): overall_progress
export interface StageEvent {
  job_id: string;
  stage: Stage;
  /** 'started' | 'progress' | 'completed' | 'failed' */
  state: string;
  message: string;
  /** Fraction within the stage. (range 0.0–1.0) */
  progress: number;
  at: Timestamp;
}

/**
 * Brand look. Replaces the separate 'color theme' and 'background color' inputs — they
 * were two controls for one decision.
 */
export interface ThemeSpec {
  /**
   * Brand hex colours. Left empty, intake extracts them from the product image. (max
   * length 6)
   */
  palette: string[];
  background: BackgroundTreatment;
  /** Only meaningful when background is seamless_color. */
  background_color: string | null;
  /** Set by intake when the palette was derived rather than supplied. */
  palette_auto_extracted: boolean;
}

/** One generated ad video, animated from an `ImageCandidate`. */
export interface VideoCandidate {
  /** At least 0. */
  index: number;
  /** Which image frame this was animated from. (at least 0) */
  source_image_index: number;
  brief: ShotBrief;
  asset: AssetRef;
  /** At least 0.0. */
  duration_seconds: number;
  /** At least 1. */
  fps: number;
  tier: Tier;
  provider: string;
  seed: number;
  /** At least 0.0. */
  cost_usd: number;
  /** At least 0. */
  latency_ms: number;
  created_at: Timestamp;
  /**
   * True when 8-10 s was reached by concatenating two ~5 s clips rather than native
   * long generation. Seam drift is measured when set.
   */
  was_chained: boolean;
  /**
   * Temporal consistency across the concatenation seam; only when chained. (range
   * 0.0–1.0)
   */
  seam_consistency: number | null;
  /**
   * What was asked for, when the provider could not deliver exactly that. Kling's
   * image-to-video endpoint takes duration as the enum {5, 10}, so a 9 s request comes
   * back — and is billed — as 10 s. (at least 0.0)
   */
  requested_duration_seconds: number | null;
  /**
   * False when the provider has no seed parameter. The image stage is reproducible and
   * the video stage may not be, and an ablation that assumes a controlled comparison
   * it never had would be reporting noise as an effect.
   */
  seed_honoured: boolean;
  score: ScoreBreakdown | null;
  thumbnail: AssetRef | null;
  /** Aspect-ratio variants keyed by ratio, e.g. '9:16'. */
  platform_renders: Record<string, AssetRef>;
}
