"""Emit the job contract as TypeScript.

The web app needs the same types the API returns.  There are three ways to get
them and only one that stays true:

1. **Hand-write them.** They are correct on the day they are written.  Then a
   field is renamed in Python, the TypeScript keeps compiling — it describes a
   shape nothing produces any more — and the mismatch surfaces as a blank cell
   in the UI weeks later.  This is the same unrecorded transcription step
   ``docs/results-protocol.md`` §1 exists to remove, and it fails the same way.
2. **Ship the OpenAPI schema through a code generator.** Correct, and it adds a
   Node toolchain dependency plus a ``$ref``-heavy intermediate file to read when
   the output is wrong.
3. **Generate them from the models, and check the committed copy for drift.**
   What this module does.

The interesting decisions are not the type mapping; they are these.

**Every field is required, and nullable where Python says so.**  A field with a
default is optional to the *constructor* and always present on the *wire*, because
``model_dump(mode="json")`` emits it.  Marking it ``?:`` in TypeScript would make
every reader write a needless existence check, and would hide a genuinely absent
field among dozens of merely defaulted ones.

**Enums emit a values array as well as a union type.**  A ``<select>`` has to
iterate the options.  Listing nine verticals by hand in a component is the drift
this module exists to prevent, one indirection later.

**Properties are named, not emitted.**  ``RankedCandidate.rank_shift`` and
``JobResult.image_stage_order`` are Python ``@property``, so they are computed on
the server and never serialised — a UI author who assumes otherwise gets
``undefined``, and if they render it into a template, the string "undefined" in
front of an examiner.  Each interface therefore carries a comment listing what
exists in Python and will *not* arrive, so the absence is documented at the point
of use rather than discovered.

**Field descriptions become JSDoc.**  Several of them are load-bearing caveats —
``ScoreBreakdown.is_stub`` explains that the number is not a prediction yet,
``GateCheck.implemented`` that a pending check always passes.  Carrying them into
the editor's tooltip puts the caveat where the person rendering the number is
looking.
"""

from __future__ import annotations

import datetime as _dt
import enum
import re
import textwrap
import types
import typing
from collections.abc import Iterable

from pydantic import BaseModel
from pydantic.fields import FieldInfo

#: Scalars with an unambiguous TypeScript equivalent.
_SCALARS: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
    bytes: "string",
}

_BANNER = """\
// Generated by scripts/export_types.py from packages/schema/adschema.
// Do not edit — regenerate.  `scripts/export_types.py --check` fails on drift.
//
// Every field below is present on the wire: pydantic's `model_dump(mode="json")`
// emits defaulted fields, so `?:` would be wrong.  `| null` means Python says the
// value can genuinely be absent.
//
// Python `@property` values are NOT serialised.  Each interface lists its own
// under `derived (not on the wire)`; those are computed in `lib/presentation.ts`
// and tested in `lib/presentation.test.ts`.

/** ISO-8601 with an offset, e.g. "2026-08-12T09:41:07.123456+00:00". */
export type Timestamp = string;
"""

#: Comment and doc wrapping width.  Matches nothing in particular; it is narrower
#: than the 100-column Python limit because JSDoc sits indented inside a brace.
_WRAP = 84


#: Sphinx roles and reStructuredText literals, which are correct in a Python
#: docstring and noise in an editor tooltip.  ``:class:`Platform``` becomes
#: `Platform`, which a TypeScript editor renders as a code span.
_ROLE = re.compile(r":(?:class|func|meth|attr|mod|data|exc):`~?([^`]+)`")
_LITERAL = re.compile(r"``([^`]+)``")


def _markup(text: str) -> str:
    """Docstring markup rewritten for JSDoc, which is Markdown."""
    text = _ROLE.sub(lambda m: f"`{m.group(1).rsplit('.', 1)[-1]}`", text)
    return _LITERAL.sub(lambda m: f"`{m.group(1)}`", text)


def _screaming_snake(name: str) -> str:
    """``AspectRatio`` -> ``ASPECT_RATIO``.

    Not cosmetic: ``ASPECTRATIO_VALUES`` is the kind of name someone retypes
    slightly differently, and an unresolved import is a build failure rather than
    the compile-time check this array exists to provide.
    """
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).upper()


def _doc(text: str, indent: str = "  ") -> list[str]:
    """One JSDoc block, wrapped — or nothing at all for an empty description."""
    if not text.strip():
        return []
    body = _markup(" ".join(text.split()))
    lines = textwrap.wrap(body, width=_WRAP - len(indent))
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    out = [f"{indent}/**"]
    out += [f"{indent} * {line}" for line in lines]
    out.append(f"{indent} */")
    return out


def _constraints(field: FieldInfo) -> str:
    """``ge``/``le``/``max_length`` as prose, for whoever has to build the input.

    A form that lets someone request a 4-second video only to have the API refuse
    it has moved a known constraint from the client to a 422.
    """
    bits: list[str] = []
    low = high = None
    for meta in field.metadata:
        for attr in ("ge", "gt"):
            value = getattr(meta, attr, None)
            if value is not None:
                low = value
        for attr in ("le", "lt"):
            value = getattr(meta, attr, None)
            if value is not None:
                high = value
        for attr, label in (("max_length", "max length"), ("min_length", "min length")):
            value = getattr(meta, attr, None)
            if value is not None:
                bits.append(f"{label} {value}")
    if low is not None and high is not None:
        bits.insert(0, f"range {low}–{high}")
    elif low is not None:
        bits.insert(0, f"at least {low}")
    elif high is not None:
        bits.insert(0, f"at most {high}")
    return "; ".join(bits)


def _properties(model: type[BaseModel]) -> list[str]:
    """Own ``@property`` names — the members that look like fields and are not."""
    return [name for name, attr in vars(model).items() if isinstance(attr, property)]


def _first_paragraph(doc: str | None) -> str:
    """The summary line only.

    A model docstring here can run to twenty lines of design rationale, which
    belongs in the Python file and not in an editor tooltip.
    """
    if not doc:
        return ""
    out: list[str] = []
    for line in doc.strip().splitlines():
        if not line.strip():
            break
        out.append(line.strip())
    return " ".join(out)


def _ts_literal(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if value is None:
        return "null"
    return str(value)


def _ts_number(value: float) -> str:
    """Integral floats print as integers: ``8``, not ``8.0``, which is not TypeScript
    style and reads as a precision claim the value does not make."""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


class Emitter:
    """Walks a set of root models and renders the transitive closure.

    Discovery order is walk order, which is deterministic given the same roots —
    the output has to be byte-stable or ``--check`` reports drift on every run and
    stops being read.
    """

    def __init__(self) -> None:
        self.models: dict[str, type[BaseModel]] = {}
        self.enums: dict[str, type[enum.Enum]] = {}

    # --- Type mapping ---

    def ts_type(self, annotation: typing.Any) -> str:
        if annotation is None or annotation is type(None):
            return "null"
        if annotation is typing.Any:
            return "unknown"
        if annotation in _SCALARS:
            return _SCALARS[annotation]
        if annotation in (_dt.datetime, _dt.date):
            return "Timestamp"

        origin = typing.get_origin(annotation)
        args = typing.get_args(annotation)

        if origin in (types.UnionType, typing.Union):
            parts = [self.ts_type(a) for a in args]
            # "null" last: `X | null` reads as the nullable X it is, where
            # `null | X` reads as a union that happens to include X.
            rest = [p for p in parts if p != "null"]
            nulls = [p for p in parts if p == "null"]
            return " | ".join(dict.fromkeys(rest + nulls))
        if origin in (list, set, frozenset):
            inner = self.ts_type(args[0]) if args else "unknown"
            return f"{inner}[]" if inner.isidentifier() else f"({inner})[]"
        if origin is tuple:
            if len(args) == 2 and args[1] is Ellipsis:
                return f"{self.ts_type(args[0])}[]"
            return "[" + ", ".join(self.ts_type(a) for a in args) + "]"
        if origin is dict:
            key = self.ts_type(args[0]) if args else "string"
            value = self.ts_type(args[1]) if len(args) > 1 else "unknown"
            # A str-enum key becomes a partial record: the API keys these by
            # platform or aspect ratio and never sends every member.
            if key != "string":
                return f"Partial<Record<{key}, {value}>>"
            return f"Record<string, {value}>"
        if origin is typing.Literal:
            return " | ".join(_ts_literal(a) for a in args)

        if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
            self.enums.setdefault(annotation.__name__, annotation)
            return annotation.__name__
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            self.register(annotation)
            return annotation.__name__
        # Anything unmapped becomes `unknown` rather than a plausible guess: a
        # wrong type that compiles is worse than one that forces a decision.
        return "unknown"

    # --- Registration ---

    def register(self, model: type[BaseModel]) -> None:
        if model.__name__ in self.models:
            return
        self.models[model.__name__] = model  # before recursing, for self-reference
        for field in model.model_fields.values():
            self.ts_type(field.annotation)

    # --- Rendering ---

    def render_enum(self, name: str, member: type[enum.Enum]) -> str:
        values = [m.value for m in member]
        union = " | ".join(_ts_literal(v) for v in values)
        lines: list[str] = []
        lines += _doc(_first_paragraph(member.__doc__), indent="")
        if len(union) + len(name) + 16 <= _WRAP:
            lines.append(f"export type {name} = {union};")
        else:
            lines.append(f"export type {name} =")
            lines += [f"  | {_ts_literal(v)}" for v in values]
            lines[-1] += ";"
        lines.append(f"export const {_screaming_snake(name)}_VALUES: readonly {name}[] = [")
        lines += [f"  {_ts_literal(v)}," for v in values]
        lines.append("];")
        return "\n".join(lines)

    def render_model(self, name: str, model: type[BaseModel]) -> str:
        lines: list[str] = []
        lines += _doc(_first_paragraph(model.__doc__), indent="")
        derived = _properties(model)
        if derived:
            lines.append(f"// derived (not on the wire): {', '.join(derived)}")
        lines.append(f"export interface {name} {{")
        for field_name, field in model.model_fields.items():
            note = field.description or ""
            limits = _constraints(field)
            if limits:
                note = f"{note} ({limits})" if note else limits[0].upper() + limits[1:] + "."
            lines += _doc(note)
            lines.append(f"  {field_name}: {self.ts_type(field.annotation)};")
        lines.append("}")
        return "\n".join(lines)

    def render(self, roots: Iterable[type[BaseModel]], constants: dict[str, float]) -> str:
        for root in roots:
            self.register(root)
        chunks = [_BANNER.rstrip()]

        chunks.append("// --- Constants ---")
        chunks.append(
            "\n".join(
                f"export const {key} = {_ts_number(value)};" for key, value in constants.items()
            )
        )

        chunks.append("// --- Enumerations ---")
        for name in sorted(self.enums):
            chunks.append(self.render_enum(name, self.enums[name]))

        chunks.append("// --- Models ---")
        for name in sorted(self.models):
            chunks.append(self.render_model(name, self.models[name]))
        return "\n\n".join(chunks) + "\n"


def generate() -> str:
    """The committed contract, from the models as they are right now."""
    from . import (
        DEFAULT_CANDIDATE_COUNT,
        MAX_DURATION_S,
        MIN_DURATION_S,
        AdJobRequest,
        AppConfig,
        BudgetStatus,
        DeliveryReport,
        DeliveryResponse,
        GoldenSummary,
        IntakeReport,
        JobRecord,
        JobResult,
        JobSummary,
        Launched,
        LedgerResponse,
        RankedCandidate,
        SpendEntry,
        StageEvent,
    )

    roots = [
        AdJobRequest,
        JobRecord,
        JobResult,
        StageEvent,
        SpendEntry,
        BudgetStatus,
        DeliveryReport,
        IntakeReport,
        RankedCandidate,
        # The HTTP envelopes. Roots in their own right rather than reachable from
        # the models above: nothing in the pipeline returns them, so without this
        # the routes the UI actually calls would be the only untyped ones left.
        AppConfig,
        GoldenSummary,
        JobSummary,
        Launched,
        LedgerResponse,
        DeliveryResponse,
    ]
    constants = {
        "MIN_DURATION_S": MIN_DURATION_S,
        "MAX_DURATION_S": MAX_DURATION_S,
        "DEFAULT_CANDIDATE_COUNT": DEFAULT_CANDIDATE_COUNT,
    }
    return Emitter().render(roots, constants)


__all__ = ["Emitter", "generate"]
