"use client";

/**
 * The frame every page sits in: navigation, the provider mode, and the budget.
 *
 * Both of those are in the header for the same reason, and it is not decoration.
 *
 * **The mode.** Mock, live and replay produce output that looks identical on
 * screen. A mock frame is a procedurally drawn placeholder; a replayed frame came
 * out of a frozen bundle; only a live frame was generated by a model just now. A
 * screenshot with no mode on it cannot be told apart, so the mode is stated on
 * every page rather than on a settings screen nobody opens.
 *
 * **The budget.** `adapi.main` puts it plainly: with $35 total, "how much is left"
 * belongs on screen at all times. It is also the number that turns a runaway loop
 * from a discovery into something visible while it is happening.
 */

import { createContext, useContext, type ReactNode } from "react";

import { getBudget, getConfig } from "@/lib/api.ts";
import type { AppConfig, ProviderMode } from "@/lib/contract.ts";
import { useAsync, usePolled } from "@/lib/hooks.ts";
import { budgetView, percent, usd } from "@/lib/presentation.ts";
import { Badge, Meter, NavLink, type Tone } from "./ui.tsx";

const ConfigContext = createContext<AppConfig | null>(null);

/** The app config, or null while it loads. Pages that need platform geometry use it. */
export const useConfig = () => useContext(ConfigContext);

/**
 * Keyed by the generated `ProviderMode` rather than by `string`.
 *
 * The difference matters the day a fourth mode is added: with `string` keys a
 * missing entry falls back to a neutral grey badge and the new mode ships looking
 * exactly as safe as mock. With the enum, TypeScript refuses to compile until
 * someone decides what colour it is.
 */
const MODE_TONE: Record<ProviderMode, Tone> = { mock: "warn", replay: "info", live: "bad" };

const MODE_MEANING: Record<ProviderMode, string> = {
  mock: "Frames and clips are drawn locally. Nothing was generated by a model.",
  replay: "Output comes from a frozen golden bundle. No network, no spend.",
  live: "Real provider calls. Every generation on this page cost money.",
};

export function Shell({ children }: { children: ReactNode }) {
  const config = useAsync(getConfig, []);
  // Ten seconds, not five: a job that spends takes tens of seconds, so this is
  // responsive enough to watch the money move, and half the idle chatter.
  const budget = usePolled(getBudget, 10_000);
  const mode = config.data?.provider_mode ?? null;
  const view = budget.data ? budgetView(budget.data) : null;

  return (
    <ConfigContext.Provider value={config.data}>
      <div className="mx-auto max-w-6xl px-5 py-6">
        <header className="mb-6 border-b border-zinc-800 pb-4">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <span className="text-sm font-semibold text-zinc-100">
                Multi-candidate ad generation
              </span>
              <nav className="flex items-center gap-1">
                <NavLink href="/">New job</NavLink>
                <NavLink href="/jobs">Jobs</NavLink>
              </nav>
            </div>

            <div className="flex items-center gap-4">
              {mode ? (
                <Badge tone={MODE_TONE[mode]} title={MODE_MEANING[mode]}>
                  {mode} mode
                </Badge>
              ) : null}

              {view && budget.data ? (
                <div className="w-44">
                  <div className="mb-1 flex items-baseline justify-between text-[11px] text-zinc-400">
                    <span>{usd(view.remaining)} left</span>
                    <span className="tabular">{percent(view.fractionUsed)} used</span>
                  </div>
                  <Meter
                    fraction={view.fractionUsed}
                    tone={view.level === "spent" ? "bad" : view.level === "tight" ? "warn" : "good"}
                  />
                  <p className="mt-1 text-[10px] text-zinc-500 tabular">
                    {usd(budget.data.spent_usd)} of {usd(budget.data.total_budget_usd)} · cap{" "}
                    {usd(budget.data.per_job_cap_usd)}/job
                  </p>
                </div>
              ) : null}
            </div>
          </div>

          {/* The settings banner verbatim: it names the providers actually wired up,
              which is the difference between "live mode" and "live mode, but the
              video provider fell back". */}
          {config.data ? (
            <p className="mt-3 font-mono text-[11px] leading-relaxed text-zinc-500">
              {config.data.banner}
            </p>
          ) : null}
          {config.error ? (
            <p className="mt-3 text-[11px] text-bad-400">
              {config.error} — the pages below will be empty until it is.
            </p>
          ) : null}
        </header>

        <main>{children}</main>

        <footer className="mt-12 border-t border-zinc-800 pt-4 text-[11px] leading-relaxed text-zinc-600">
          Candidate scores are predictions, not measurements. Anything marked{" "}
          <span className="text-warn-400">▲</span> is a placeholder or an unverified check — see{" "}
          <span className="font-mono">docs/ui-protocol.md</span>.
        </footer>
      </div>
    </ConfigContext.Provider>
  );
}
