"""Report figures, drawn as SVG with nothing but the standard library.

There is no matplotlib here, and that is a constraint rather than a preference:
this laptop has 8 GB of RAM and under 10 GB of free disk, matplotlib plus its
dependencies is a few hundred megabytes, and the same disk budget already went on
the parts of the project that cannot be done any other way.  The four figures the
write-up needs are bar-and-whisker plots and a scatter, which is a few hundred
lines of coordinate arithmetic — cheaper than the dependency and, unlike a notebook
cell, regenerated by the same command that produces the tables.

Two decisions in here are about honesty rather than drawing.

**A figure refuses to imply a precision it does not have.**  Every interval is
drawn, never omitted, and a value with no interval is drawn hollow with the reason
written on the axis.  A bar chart of point estimates is the single most misleading
artefact this project could produce, because the intervals at this corpus size are
wider than every difference between models.

**A figure carries its own caveat.**  :func:`caption` stamps the label source and
the sample size into the SVG itself, so an image pasted into a slide deck arrives
with its provenance attached rather than losing it in transit.  A figure built from
stub scores says so in its subtitle, in the same red the axis warnings use.

SVG rather than PNG because it is text: it diffs, it scales into a printed report
without resampling, and it needs no image library to write.  A viewer that wants a
raster can convert one; nothing in the pipeline needs to.
"""

from __future__ import annotations

import html
import math
from collections.abc import Sequence
from dataclasses import dataclass, field

# --- Palette ----------------------------------------------------------------
# Chosen to stay legible printed in greyscale, which a bound report usually is:
# the two series differ in lightness as well as hue.

INK = "#1c1c1c"
MUTED = "#6b6b6b"
GRID = "#d8d8d8"
ACCENT = "#2b3a55"
ACCENT_LIGHT = "#7d8ca8"
WARN = "#a8322d"
GOOD = "#2f6b4f"
PAPER = "#ffffff"

FONT = "system-ui, -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"
MONO = "ui-monospace, 'SF Mono', Menlo, Consolas, monospace"

#: Where a title and its caveat line start.  Deliberately the figure's own margin
#: rather than the plot area's left edge: the plot's left edge sits a long way in to
#: leave room for row labels, and titles anchored there ran off the right of the
#: canvas.
MARGIN = 20.0

#: Rough advance width per character, as a fraction of font size, for the one thing
#: that needs it: deciding whether a value label still fits before the right edge.
#: A real text metric would need a font library; being approximately right here only
#: risks flipping a label that would have fitted.
CHAR_WIDTH = 0.55


def _esc(text: str) -> str:
    return html.escape(str(text), quote=True)


def _num(value: float) -> str:
    """Coordinates at two decimals: enough for sub-pixel placement, and it keeps
    the SVG diffable instead of churning on floating-point noise."""
    return f"{value:.2f}".rstrip("0").rstrip(".") or "0"


def _finite(value: float | None) -> bool:
    return value is not None and not math.isnan(value) and not math.isinf(value)


@dataclass
class Figure:
    """An SVG document being assembled.

    Deliberately not a general drawing library — it has exactly the primitives the
    four report figures need. Anything more would be a second matplotlib, badly.
    """

    width: float
    height: float
    parts: list[str] = field(default_factory=list)

    def text(
        self,
        x: float,
        y: float,
        content: str,
        *,
        size: float = 12,
        fill: str = INK,
        anchor: str = "start",
        weight: str = "normal",
        mono: bool = False,
        opacity: float = 1.0,
    ) -> None:
        family = MONO if mono else FONT
        self.parts.append(
            f'<text x="{_num(x)}" y="{_num(y)}" font-family="{family}" '
            f'font-size="{_num(size)}" fill="{fill}" text-anchor="{anchor}" '
            f'font-weight="{weight}" opacity="{_num(opacity)}">{_esc(content)}</text>'
        )

    def value_label(
        self, x: float, y: float, content: str, *, size: float = 9.5, fill: str = MUTED
    ) -> None:
        """A small label beside a mark, flipped inward when it would leave the canvas.

        The mark furthest right is usually the best model or the largest effect, so
        without the flip the row that matters most is the row whose number is
        unreadable.
        """
        if x + 10 + len(content) * size * CHAR_WIDTH > self.width - MARGIN:
            self.text(x - 10, y, content, size=size, fill=fill, anchor="end")
        else:
            self.text(x + 10, y, content, size=size, fill=fill)

    def rotated_text(
        self, x: float, y: float, content: str, *, size: float = 11, fill: str = INK
    ) -> None:
        """A quarter-turn label, for a vertical axis.

        Its own method because an SVG ``rotate(angle cx cy)`` has to close its own
        bracket inside an f-string, which is easy to get wrong twice.
        """
        pivot = f"{_num(x)} {_num(y)}"
        self.parts.append(
            f'<text x="{_num(x)}" y="{_num(y)}" font-family="{FONT}" '
            f'font-size="{_num(size)}" fill="{fill}" text-anchor="middle" '
            f'transform="rotate(-90 {pivot})">{_esc(content)}</text>'
        )

    def line(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        *,
        stroke: str = GRID,
        width: float = 1.0,
        dash: str | None = None,
    ) -> None:
        dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
        self.parts.append(
            f'<line x1="{_num(x1)}" y1="{_num(y1)}" x2="{_num(x2)}" y2="{_num(y2)}" '
            f'stroke="{stroke}" stroke-width="{_num(width)}"{dash_attr} />'
        )

    def rect(
        self,
        x: float,
        y: float,
        w: float,
        h: float,
        *,
        fill: str = ACCENT,
        stroke: str | None = None,
        opacity: float = 1.0,
        radius: float = 0.0,
    ) -> None:
        stroke_attr = f' stroke="{stroke}" stroke-width="1"' if stroke else ""
        self.parts.append(
            f'<rect x="{_num(x)}" y="{_num(y)}" width="{_num(max(w, 0))}" '
            f'height="{_num(max(h, 0))}" rx="{_num(radius)}" fill="{fill}" '
            f'opacity="{_num(opacity)}"{stroke_attr} />'
        )

    def circle(
        self, cx: float, cy: float, r: float, *, fill: str = ACCENT, stroke: str | None = None
    ) -> None:
        stroke_attr = f' stroke="{stroke}" stroke-width="1.5"' if stroke else ""
        self.parts.append(
            f'<circle cx="{_num(cx)}" cy="{_num(cy)}" r="{_num(r)}" fill="{fill}"{stroke_attr} />'
        )

    def whisker(self, x_lo: float, x_hi: float, y: float, *, stroke: str = INK, cap: float = 4.0):
        """A horizontal interval with end caps.

        Always drawn. An accuracy without its interval is the thing this whole
        module exists to make awkward to produce.
        """
        self.line(x_lo, y, x_hi, y, stroke=stroke, width=1.6)
        self.line(x_lo, y - cap, x_lo, y + cap, stroke=stroke, width=1.6)
        self.line(x_hi, y - cap, x_hi, y + cap, stroke=stroke, width=1.6)

    def render(self, *, title: str = "") -> str:
        head = (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {_num(self.width)} {_num(self.height)}" '
            f'width="{_num(self.width)}" height="{_num(self.height)}" '
            f'role="img" aria-label="{_esc(title)}">'
        )
        titled = f"<title>{_esc(title)}</title>" if title else ""
        background = (
            f'<rect width="{_num(self.width)}" height="{_num(self.height)}" fill="{PAPER}" />'
        )
        return head + titled + background + "".join(self.parts) + "</svg>\n"


@dataclass
class Provenance:
    """What a figure has to admit about itself.

    Rendered into the figure's subtitle so a copied image keeps its caveats. The
    fields mirror the ones the tables carry, so a figure and its table cannot
    disagree about whether the data is real.
    """

    n: int
    unit: str = "comparisons"
    labels_are_real: bool = True
    features_are_real: bool = True
    note: str = ""

    def caption(self) -> str:
        parts = [f"n = {self.n} {self.unit}"]
        if not self.labels_are_real:
            parts.append("SIMULATED LABELS — NOT A RESULT")
        if not self.features_are_real:
            parts.append("STAND-IN FEATURES — NOT A RESULT")
        if self.note:
            parts.append(self.note)
        return "  ·  ".join(parts)

    @property
    def is_a_result(self) -> bool:
        return self.labels_are_real and self.features_are_real


def _frame(
    fig: Figure,
    *,
    title: str,
    provenance: Provenance,
    left: float,
    right: float,
    top: float,
    bottom: float,
) -> None:
    """Title, caveat line and plot border, shared by every figure."""
    fig.text(MARGIN, 24, title, size=15, weight="600")
    fig.text(
        MARGIN,
        42,
        provenance.caption(),
        size=11,
        fill=INK if provenance.is_a_result else WARN,
        weight="normal" if provenance.is_a_result else "600",
    )
    fig.line(left, bottom, right, bottom, stroke=MUTED, width=1.2)
    fig.line(left, top, left, bottom, stroke=MUTED, width=1.2)


def _x_axis(
    fig: Figure,
    *,
    lo: float,
    hi: float,
    left: float,
    right: float,
    bottom: float,
    top: float,
    ticks: Sequence[float],
    label: str,
    fmt: str = "{:.2f}",
) -> None:
    for tick in ticks:
        x = left + (tick - lo) / (hi - lo) * (right - left)
        fig.line(x, top, x, bottom, stroke=GRID)
        fig.text(x, bottom + 16, fmt.format(tick), size=10, fill=MUTED, anchor="middle")
    fig.text((left + right) / 2, bottom + 34, label, size=11, fill=INK, anchor="middle")


# --- 1. Accuracy against the ceiling ----------------------------------------


@dataclass
class ModelPoint:
    """One row of the model comparison: a scorer, its accuracy and its interval."""

    label: str
    accuracy: float
    ci: tuple[float, float]
    n: int = 0
    is_trained: bool = False


def accuracy_forest(
    points: Sequence[ModelPoint],
    *,
    provenance: Provenance,
    ceiling: float | None = None,
    chance: float = 0.5,
    title: str = "Held-out pairwise accuracy",
    width: float = 720,
) -> str:
    """Models as a forest plot, against chance and against the noise ceiling.

    A forest plot rather than bars because the comparison that matters is whether
    the intervals overlap, and bars invite reading the tops of two rectangles as a
    difference.  The ceiling is drawn as a line and labelled: accuracy against 1.0
    is the wrong denominator when the labels are single noisy human judgements.
    """
    left, right, top = 190.0, width - 30.0, 64.0
    row_h = 30.0
    bottom = top + max(len(points), 1) * row_h
    fig = Figure(width, bottom + 78)
    _frame(fig, title=title, provenance=provenance, left=left, right=right, top=top, bottom=bottom)

    lo, hi = 0.3, 1.0
    finite = [v for p in points for v in (p.accuracy, *p.ci) if _finite(v)]
    if finite:
        lo = min(0.3, math.floor(min(finite) * 20) / 20)
    span = hi - lo

    def x_of(value: float) -> float:
        return left + (value - lo) / span * (right - left)

    ticks = [t / 100 for t in range(int(lo * 100), 101, 10)]
    _x_axis(
        fig,
        lo=lo,
        hi=hi,
        left=left,
        right=right,
        bottom=bottom,
        top=top,
        ticks=ticks,
        label="pairwise accuracy",
    )

    # Chance first so everything else sits above it.
    fig.line(x_of(chance), top, x_of(chance), bottom, stroke=MUTED, width=1.2, dash="4 3")
    fig.text(x_of(chance), top - 6, f"chance {chance:.2f}", size=10, fill=MUTED, anchor="middle")

    if _finite(ceiling):
        fig.line(x_of(ceiling), top, x_of(ceiling), bottom, stroke=GOOD, width=1.4, dash="6 3")
        fig.text(
            x_of(ceiling), top - 6, f"ceiling {ceiling:.3f}", size=10, fill=GOOD, anchor="middle"
        )

    for i, point in enumerate(points):
        y = top + i * row_h + row_h / 2
        weight = "600" if point.is_trained else "normal"
        fig.text(left - 10, y + 4, point.label, size=11, anchor="end", weight=weight, mono=True)

        if not _finite(point.accuracy):
            fig.text(left + 8, y + 4, "not measured", size=11, fill=WARN, anchor="start")
            continue

        colour = ACCENT if point.is_trained else ACCENT_LIGHT
        ci_lo, ci_hi = point.ci
        if _finite(ci_lo) and _finite(ci_hi):
            fig.whisker(x_of(ci_lo), x_of(ci_hi), y, stroke=colour)
            fig.circle(x_of(point.accuracy), y, 4.5, fill=colour)
        else:
            # Hollow: a point estimate with no interval behind it. The shape is the
            # warning, so it survives being cropped out of the caption.
            fig.circle(x_of(point.accuracy), y, 4.5, fill=PAPER, stroke=WARN)
            fig.text(right - 4, y + 4, "no interval", size=9, fill=WARN, anchor="end")

        label = f"{point.accuracy:.3f}"
        if _finite(ceiling) and ceiling and ceiling > 0:
            label += f"  ({point.accuracy / ceiling:.0%} of ceiling)"
        fig.value_label(x_of(point.accuracy), y - 8, label)

    return fig.render(title=title)


# --- 2. Ablation deltas -----------------------------------------------------


@dataclass
class AblationPoint:
    """One feature group's paired effect on accuracy."""

    label: str
    delta: float
    ci: tuple[float, float]
    resolved: bool = False
    n_features: int = 0


def ablation_deltas(
    points: Sequence[AblationPoint],
    *,
    provenance: Provenance,
    title: str = "Cost of removing each feature group",
    width: float = 720,
) -> str:
    """Paired deltas against the full model, zero marked.

    Each row is *removal minus full*, so a bar to the left of zero means the group
    was carrying weight.  Rows whose interval crosses zero are drawn muted and
    labelled unresolved: at this corpus size most groups cannot be distinguished
    either way, and drawing them in the same ink as a resolved effect would invite
    reading a ranking into noise.
    """
    left, right, top = 200.0, width - 40.0, 64.0
    row_h = 28.0
    bottom = top + max(len(points), 1) * row_h
    fig = Figure(width, bottom + 78)
    _frame(fig, title=title, provenance=provenance, left=left, right=right, top=top, bottom=bottom)

    finite = [v for p in points for v in (p.delta, *p.ci) if _finite(v)]
    reach = max([abs(v) for v in finite] + [0.05]) * 1.15
    lo, hi = -reach, reach

    def x_of(value: float) -> float:
        return left + (value - lo) / (hi - lo) * (right - left)

    step = 0.05 if reach <= 0.25 else 0.1
    n_ticks = int(reach / step)
    ticks = [i * step for i in range(-n_ticks, n_ticks + 1)]
    _x_axis(
        fig,
        lo=lo,
        hi=hi,
        left=left,
        right=right,
        bottom=bottom,
        top=top,
        ticks=ticks,
        label="change in accuracy when the group is removed",
        fmt="{:+.2f}",
    )

    fig.line(x_of(0), top, x_of(0), bottom, stroke=INK, width=1.2)

    for i, point in enumerate(points):
        y = top + i * row_h + row_h / 2
        name = point.label if not point.n_features else f"{point.label} ({point.n_features})"
        fig.text(left - 10, y + 4, name, size=11, anchor="end", mono=True)

        if not _finite(point.delta):
            fig.text(x_of(0) + 8, y + 4, "not measured", size=10, fill=WARN)
            continue

        colour = ACCENT if point.resolved else ACCENT_LIGHT
        ci_lo, ci_hi = point.ci
        if _finite(ci_lo) and _finite(ci_hi):
            fig.whisker(x_of(ci_lo), x_of(ci_hi), y, stroke=colour)
        fig.circle(x_of(point.delta), y, 4.0, fill=colour)
        # The exact delta, so the figure is readable without its table beside it.
        fig.value_label(x_of(point.delta), y - 8, f"{point.delta:+.3f}")
        if not point.resolved:
            fig.text(right - 4, y + 4, "unresolved", size=9, fill=MUTED, anchor="end")

    return fig.render(title=title)


# --- 3. Stage agreement -----------------------------------------------------


def stage_scatter(
    pairs: Sequence[tuple[int, int]],
    *,
    provenance: Provenance,
    rho: float | None = None,
    n_candidates: int = 3,
    title: str = "Image-stage rank vs video-stage rank",
    width: float = 460,
) -> str:
    """Where each candidate sat at each stage, as a counted grid.

    A jittered scatter would be unreadable at three-by-three, so cells are counted
    and the count sizes the mark: the diagonal filling up means the image stage
    predicted the final order, and mass off the diagonal means animation reordered
    things.  The diagonal is drawn so "did it stay put" is answerable at a glance
    without reading the correlation.
    """
    left, top = 78.0, 78.0
    cell = 74.0
    right = left + n_candidates * cell
    bottom = top + n_candidates * cell
    fig = Figure(max(width, right + 40), bottom + 92)
    _frame(fig, title=title, provenance=provenance, left=left, right=right, top=top, bottom=bottom)

    counts: dict[tuple[int, int], int] = {}
    for image_rank, video_rank in pairs:
        if 0 <= image_rank < n_candidates and 0 <= video_rank < n_candidates:
            counts[(image_rank, video_rank)] = counts.get((image_rank, video_rank), 0) + 1
    busiest = max(counts.values(), default=1)

    for i in range(n_candidates + 1):
        offset = i * cell
        fig.line(left, top + offset, right, top + offset, stroke=GRID)
        fig.line(left + offset, top, left + offset, bottom, stroke=GRID)

    fig.line(left, top, right, bottom, stroke=GOOD, width=1.2, dash="5 4")

    for i in range(n_candidates):
        centre = left + i * cell + cell / 2
        fig.text(centre, bottom + 18, f"#{i + 1}", size=11, fill=MUTED, anchor="middle")
        fig.text(
            left - 12, top + i * cell + cell / 2 + 4, f"#{i + 1}", size=11, fill=MUTED, anchor="end"
        )

    fig.text((left + right) / 2, bottom + 38, "image-stage rank", size=11, anchor="middle")
    fig.rotated_text(left - 44, (top + bottom) / 2, "video-stage rank")

    for (image_rank, video_rank), count in sorted(counts.items()):
        cx = left + image_rank * cell + cell / 2
        cy = top + video_rank * cell + cell / 2
        # Area proportional to the count, so two marks compare by area rather than
        # by radius — the usual way a bubble chart exaggerates.
        radius = 9 + 17 * math.sqrt(count / busiest)
        on_diagonal = image_rank == video_rank
        fig.circle(cx, cy, radius, fill=GOOD if on_diagonal else ACCENT)
        fig.text(cx, cy + 5, str(count), size=13, fill=PAPER, anchor="middle", weight="600")

    if not counts:
        fig.text(
            (left + right) / 2,
            (top + bottom) / 2,
            "no paired observations",
            size=12,
            fill=WARN,
            anchor="middle",
        )
    if _finite(rho):
        fig.text(left, bottom + 62, f"mean Spearman rho = {rho:+.3f}", size=11, mono=True)
    else:
        fig.text(
            left,
            bottom + 62,
            "rho withheld: too few sets for an interval",
            size=11,
            fill=WARN,
            mono=True,
        )
    return fig.render(title=title)


# --- 4. What sample size buys -----------------------------------------------


def sample_size_curve(
    points: Sequence[tuple[int, float]],
    *,
    provenance: Provenance,
    marks: Sequence[tuple[int, str]] = (),
    target: float | None = None,
    title: str = "Interval width against corpus size",
    width: float = 640,
) -> str:
    """Half-width of the accuracy interval as the corpus grows.

    The figure that justifies the generation spend.  ``marks`` annotates specific
    corpus sizes — where the corpus is now, and where it needs to be — and
    ``target`` draws the width below which the model differences become resolvable.
    Without this curve "we need 100 sets" is an assertion; with it, it is read off
    an axis.
    """
    left, right, top = 74.0, width - 30.0, 66.0
    bottom = top + 230.0
    fig = Figure(width, bottom + 84)
    _frame(fig, title=title, provenance=provenance, left=left, right=right, top=top, bottom=bottom)

    usable = [(n, w) for n, w in points if n > 0 and _finite(w)]
    if not usable:
        fig.text(
            (left + right) / 2,
            (top + bottom) / 2,
            "no measurements",
            size=12,
            fill=WARN,
            anchor="middle",
        )
        return fig.render(title=title)

    x_lo = min(n for n, _ in usable)
    x_hi = max(n for n, _ in usable)
    y_hi = max(w for _, w in usable) * 1.1
    x_span = max(x_hi - x_lo, 1)

    def x_of(n: float) -> float:
        return left + (n - x_lo) / x_span * (right - left)

    def y_of(w: float) -> float:
        return bottom - (w / y_hi) * (bottom - top)

    for i in range(5):
        w = y_hi * i / 4
        y = y_of(w)
        fig.line(left, y, right, y, stroke=GRID)
        fig.text(left - 8, y + 4, f"{w:.03f}", size=10, fill=MUTED, anchor="end", mono=True)
    fig.text(
        (left + right) / 2, bottom + 34, "generation sets in the corpus", size=11, anchor="middle"
    )
    fig.rotated_text(left - 52, (top + bottom) / 2, "95% half-width")

    if _finite(target):
        fig.line(left, y_of(target), right, y_of(target), stroke=GOOD, width=1.3, dash="6 3")
        fig.text(
            right - 4,
            y_of(target) - 6,
            f"resolvable below {target:.03f}",
            size=10,
            fill=GOOD,
            anchor="end",
        )

    path = " ".join(
        f"{'M' if i == 0 else 'L'}{_num(x_of(n))},{_num(y_of(w))}"
        for i, (n, w) in enumerate(sorted(usable))
    )
    fig.parts.append(
        f'<path d="{path}" fill="none" stroke="{ACCENT}" stroke-width="2" '
        f'stroke-linejoin="round" />'
    )
    for n, w in sorted(usable):
        fig.circle(x_of(n), y_of(w), 3.4, fill=ACCENT)

    for n, label in marks:
        if not x_lo <= n <= x_hi:
            continue
        x = x_of(n)
        fig.line(x, top, x, bottom, stroke=WARN, width=1.1, dash="3 3")
        fig.text(x, top - 6, label, size=10, fill=WARN, anchor="middle")
        fig.text(x, bottom + 16, str(n), size=10, fill=WARN, anchor="middle", mono=True)

    for n, _ in sorted(usable):
        if any(n == m for m, _ in marks):
            continue
        fig.text(x_of(n), bottom + 16, str(n), size=10, fill=MUTED, anchor="middle", mono=True)

    return fig.render(title=title)
